### ISSUE TITLE
QA_Searching and Sorting_Indroduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#104]
Defect Description:
In the introduction page of "Searching and Sorting" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the introduction page of "Searching and Sorting" experiment,when we click on the feedback link it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Searching%20and%20Sorting/Searching%20and%20Sorting_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11435860/dba4a612-9504-11e5-9c88-24d88b9d7622.png)

**Comment by sravanthimodepu** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
