### ISSUE TITLE
QA_Searching and Sorting_Back to experiments

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#115]
Defect Description:
In the "Searching and Sorting" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  .

Actual Result:
In the "Searching and Sorting" experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Searching%20and%20Sorting/Searching%20and%20Sorting_29_Back%20to%20experiments_smk.org

![12](https://cloud.githubusercontent.com/assets/14869397/11437142/2ee3386e-9511-11e5-8019-7b44f2afc5f0.png)

**Comment by sadhanareddy** [comment]
Fixed.This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
