### ISSUE TITLE
QA_Permutation_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#118]
Defect Description:
In the introduction page of "Permutation" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the introduction page of "Permutation" experiment,when we click on the feedback link it is redirecting to an error page(404) .

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Permutation/Permutation_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11437263/7166508a-9512-11e5-9bb4-cf329e8023aa.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine and it is redirecting to the Feedback Form. This issue was related to #145 .

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
