### ISSUE TITLE
QA_Sequences_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#132]
Defect Description:
In the introduction page of "Sequences" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the introduction page of "Sequences" experiment,when we click on the feedback link it is redirecting to an error page(404) .

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Sequences/Sequences_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11437803/95eb655e-9516-11e5-90ca-cf913f0f3122.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback form is available now. This issue was related to issue #145 .

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
