### ISSUE TITLE
QA_Sequences_Back to experiments

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#143]
Defect Description:
In the "Sequences" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  .

Actual Result:
In the "Sequences" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Sequences/Sequences_29_Back%20to%20experiments_smk.org

![12](https://cloud.githubusercontent.com/assets/14869397/11438332/35bd1764-951a-11e5-9953-a5cb7b9484de.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
