### ISSUE TITLE
QA_problem-solving_Feedback

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#144]
Defect Description:
In the landing page of "Problem Solving Lab" Lab,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the landing page of "Problem Solving Lab" Lab,when we click on the feedback link it is redirecting to an error page(404)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/system/problem-solving_08_Feedback_smk.org

![404](https://cloud.githubusercontent.com/assets/14869397/11438367/628e6db0-951a-11e5-87a8-184d3f687796.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine and redirecting to Feedback form. This issue was related to issue #145 .

**Comment by kolliSuman** [comment]
When we click on the feedback link, it is redirecting to the wrong URL(feedback.vlabs.ac.in) instead it should redirect to the hosted URL(feedback.base1.vlabs.ac.in).

![feedback](https://cloud.githubusercontent.com/assets/14869397/13135556/ad2019b0-d637-11e5-9aa7-31da65d292ad.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
