### ISSUE TITLE
QA_problem-solving_URL

### ISSUE THREAD

**Issue by varshanihanth** [Virtual-Labs/problem-solving-iiith#145]
Defect Description:
The UI of the Problem Solving Lab is different from one institute link,Disciplines and Domains link and from the featured labs instead the UI of the lab should be same when we open the lab from institute link,Disciplines and Domains link and from the featured labs

URL:
Institute: http://cse04-iiith.virtual-labs.ac.in/
Disciplines and Domains : http://ps-iiith.vlabs.ac.in/
Featured Labs : http://ps-iiith.vlabs.ac.in/

Attachment:
![psl-f d](https://cloud.githubusercontent.com/assets/14229099/12190451/acd40836-b5ee-11e5-8b80-2c6cb82fe903.png)
![psl_inst](https://cloud.githubusercontent.com/assets/14229099/12190452/acda796e-b5ee-11e5-9ddd-4d5e234c81b2.png)

**Comment by khushpreet-kaur** [comment]
Link has been updated on landing page. Please follow the URL : https://vlabs.ac.in

**Comment by varshanihanth** [comment]
@khushpreet Kindly add the status label for this issue

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
