### ISSUE TITLE
 QA_Numerical Representation_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#146]
Defect Description:
When we click on the Quizzes link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Quizzes link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Numerical%20Representation/Numerical%20Representation_18_Quiz_smk.org

![exp1-1](https://cloud.githubusercontent.com/assets/14869397/13102468/c8d6197a-d574-11e5-85ec-f83629495f55.png)

![exp1-2](https://cloud.githubusercontent.com/assets/14869397/13102472/ce7da4b0-d574-11e5-9c85-84e631ceeb65.png)

**Comment by BSravanthi** [comment]
Issue is fixed.

**Comment by sadhanareddy** [comment]
Issue is fixed. Hence closing the issue.
