### ISSUE TITLE
QA_Beauty of Numbers_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#150]
Defect Description:
When we click on the Objective link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Objective link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Beauty%20of%20Numbers/Beauty%20of%20Numbers_05_Objective_smk.org

![exp2-1](https://cloud.githubusercontent.com/assets/14869397/13104661/617e442c-d584-11e5-9f8c-aa33f9f94d24.png)

![exp2-2](https://cloud.githubusercontent.com/assets/14869397/13104669/69e2518a-d584-11e5-9510-68901dc8f486.png)

**Comment by BSravanthi** [comment]
Issue is resolved.

**Comment by sadhanareddy** [comment]
Issue is fixed. Hence closing the issue.
