### ISSUE TITLE
QA_Numerical Representation_back to experiments

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#16]
Defect Description:
In the "Numerical Representation" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  

Actual Result:
In the "Numerical Representation" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Numerical%20Representation/Numerical%20Representation_29_Back%20to%20experiments_smk.org

![13](https://cloud.githubusercontent.com/assets/14869397/11266739/b75918ee-8ecc-11e5-89d2-6d2683841f20.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.
