### ISSUE TITLE
QA_String Operations_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#161]
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/String%20Operations/String%20Operations_04_Theory_smk.org

![exp5-1](https://cloud.githubusercontent.com/assets/14869397/13105676/68a0c382-d58a-11e5-94ef-8256c82df398.png)

![exp5-2](https://cloud.githubusercontent.com/assets/14869397/13105684/716f321e-d58a-11e5-8edb-84f12572b4fd.png)

**Comment by BSravanthi** [comment]
This issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is fixed now.

**Comment by sadhanareddy** [comment]
Issue is fixed. Hence closing the issue.
