### ISSUE TITLE
QA_Numerical Representation_UI

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#17]
Defect Description:
In the "Numerical Representation" experiment,the 'Home' &'Problem Solving Lab' links are present outside of the page width instead the links should be placed within the page limit inorder to maintain the page utility 

Actual Result:
In the "Numerical Representation" experiment,the 'Home' &'Problem Solving Lab' links are placed outside of the page width

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Numerical%20Representation/Numerical%20Representation_01_Usability_smk.org

![14](https://cloud.githubusercontent.com/assets/14869397/11266770/1310ea22-8ecd-11e5-907e-a9a609cbf69a.png)

**Comment by khushpreet-kaur** [comment]
Fixed. This bug is related to issue #145
