### ISSUE TITLE
QA_Permutation_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#178]
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Permutation/Permutation_04_Theory_smk.org

![exp9-1](https://cloud.githubusercontent.com/assets/14869397/13133840/81101436-d625-11e5-9331-b77afedc02c3.png)

![exp9-2](https://cloud.githubusercontent.com/assets/14869397/13133846/89025834-d625-11e5-9719-584f8e444581.png)

**Comment by BSravanthi** [comment]
The issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is fixed now.

**Comment by sadhanareddy** [comment]
Issue is fixed. Hence closing the issue.
