### ISSUE TITLE
QA_Beauty of Numbers_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#18]
Defect Description:
In the introduction page of "Beauty of Numbers" experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory

Actual Result:
In the introduction page of "Beauty of Numbers" experiment,the alignment of the feedback link is not clear

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Beauty%20of%20Numbers/Beauty%20of%20Numbers_02_Introduction_smk.org

![1](https://cloud.githubusercontent.com/assets/14869397/11358059/a1bc0642-9294-11e5-9503-5a89ea8d2086.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.
