### ISSUE TITLE
QA_problem-solving_Feedback

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#187]
Defect Description:
When we click on the feedback link, it is redirecting to the wrong URL(feedback.vlabs.ac.in) instead it should redirect to the hosted URL(feedback.base1.vlabs.ac.in).

Actual Result:
When we click on the feedback link, it is redirecting to the wrong URL(feedback.vlabs.ac.in)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/system/problem-solving_08_Feedback_smk.org

![e3c2dff8-d627-11e5-9373-f25c374c48f8](https://cloud.githubusercontent.com/assets/14869397/13166016/1dd8eb08-d6e9-11e5-89f8-c5b382bba348.png)

**Comment by lalitsanagavarapu** [comment]
Feedback link pointing to vlabs.ac.in will continue, we will make it configurable as we start working on redesign the labs
