### ISSUE TITLE
QA_String Operations_Manual

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#188]
Defect Description:
When we click on the Manual link, it is redirecting to an error page instead it should redirect to manual page of String Operations experiment .

Actual Result:
When we click on the Manual link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

![exp5](https://cloud.githubusercontent.com/assets/14869397/13418006/129a737c-df97-11e5-9a7b-1d75099abfc4.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved.

**Comment by varshanihanth** [comment]
As there is no manual page requirement for this experiment, QA team is closing this issue
