### ISSUE TITLE
QA_Beauty of Numbers_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#19]
Defect Description:
In the introduction page of "Beauty of Numbers" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened

Actual Result:
In the introduction page of "Beauty of Numbers" experiment,when we click on the feedback link it is redirecting to an error page(404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Beauty%20of%20Numbers/Beauty%20of%20Numbers_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11358073/db9f3212-9294-11e5-83ac-ca9ccec9fb2e.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine. It is redirecting to the Feedback Form. This issue is related to issue #145 .
