### ISSUE TITLE
QA_Problem solving_Experiment

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#222]
Defect Description:
when we click on the about button a popup box is displayed with short-cut keys , in that ctrl+q is given to close the popup but when when we press ctrl+q the browser is getting  closed instead popup should get closed  .

Actual Result:
when we click on the about button a popup box is displayed with short-cut keys , in that ctrl+q is given to close the popup but when when we press ctrl+q the browser is getting  closed

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Comment by khushpreet-kaur** [comment]
We are using online library to get edit Area for this simulation. It is a huge library with compressed code. Tweak the code is not possible in this scenario. Therefore differing this issue.
