### ISSUE TITLE
Content and broken links of footer. 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/problem-solving-iiith#253]
Content in the footer of "exp1/Experiment page" is not same as the other experiments page footers. 
In experiment 2/Further Readings image links of the footer are broken.

**Comment by BSravanthi** [comment]
The issue is resolved. In the Experiment page of  Numerical Representation, Content in the footer is adjusted and the logos in the footer of Further readings page in  Beauty of Numbers are updated.
