### ISSUE TITLE
Consistency of the links in pages

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/problem-solving-iiith#259]
As there is same procedure, Further readings and manual content, given for this lab experiments, it should be given as links  in all the experiments. In experiment 1, 5, 8, 9, 10 these links are missing.

**Comment by BSravanthi** [comment]
The issue is fixed. The Procedure, Further Readings and the Manual links are added to all the experiment pages of 1,5,8,9 and 10.
