### ISSUE TITLE
QA_Beauty of Numbers_Back to experiments

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#30]
Defect Description:
In the "Beauty of Numbers" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  

Actual Result:
In the "Beauty of Numbers" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Beauty%20of%20Numbers/Beauty%20of%20Numbers_30_Back%20to%20experiments_smk.org

![11](https://cloud.githubusercontent.com/assets/14869397/11358571/b576d716-9299-11e5-970a-81f7590653b4.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
