### ISSUE TITLE
QA_More on Numbers_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#33]
Defect Description:
In the introduction page of "More on Numbers" experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory.

Actual Result:
In the introduction page of "More on Numbers" experiment,the alignment of the feedback link is not clear.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/More%20on%20Numbers/More%20on%20Numbers_02_Introduction_smk.org

![2](https://cloud.githubusercontent.com/assets/14869397/11362605/d5b96b1c-92ba-11e5-8f67-f85b97cfc945.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
