### ISSUE TITLE
QA_More on Numbers_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#34]
Defect Description:
In the introduction page of "More on Numbers" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the introduction page of "More on Numbers" experiment,when we click on the feedback link it is redirecting to an error page(404) .

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/More%20on%20Numbers/More%20on%20Numbers_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11362659/2b98e562-92bb-11e5-83b0-d6084123d204.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine. It is redirecting to the Feedback Form. This issue is related to issue #145 .

**Comment by BSravanthi** [comment]
Issue is fixed, so closing the issue.
