### ISSUE TITLE
QA_Problem-Solving_Quiz_Sequences_Spelling-Mistakes

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/problem-solving-iiith#341]
Defect Description :
While testing this lab, found spelling mistakes in the Quiz page of Sequences experiment.

Actual Result :
While testing this lab, found spelling mistakes in the Quiz page of Sequences experiment.
Refer to the screen shot provided in the attachments:

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_openedx_ps_i81](https://cloud.githubusercontent.com/assets/13479177/25938993/f08bdd74-364e-11e7-9706-f517cb43304d.png)

**Comment by BSravanthi** [comment]
Resolved

**Comment by sravanthimodepu** [comment]
Issue is not yet resolved. Hence reopening the issue.
