### ISSUE TITLE
QA_Problem-Solving_Procedure_Sequences_Spelling-Mistake

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/problem-solving-iiith#342]
Defect Description :
While testing this lab, found spelling mistakes in the Procedure page of Sequences experiment.

Actual Result :
While testing this lab, found spelling mistakes in the Procedure page of Sequences experiment. Please refer to the screen shot provided in attachments.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:.
![qa_openedx_ps_i82](https://cloud.githubusercontent.com/assets/13479177/25939144/791bd3f6-364f-11e7-9ea8-c676f9b19564.png)

**Comment by BSravanthi** [comment]
Corrected.

**Comment by sravanthimodepu** [comment]
Not yet corrected the spelling mistakes. Hence reopening the issue.
![pro_seq](https://user-images.githubusercontent.com/11156924/28714326-a149b8b8-73b0-11e7-83e3-c2ac6d1f9ebb.png)
