### ISSUE TITLE
problem-solving _stringoperations_experiment1

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/problem-solving-iiith#349]
Defect Description:when a input is given output is we have to check whether it is a palindrome or notexpected result:the output must be yes![Screenshot__2_](https://gitlab.com/divija123/virtual-labs-internship-divija/uploads/4fb0522dd028b76a01a6392f7bd0f7c8/Screenshot__2_.png)

**Comment by kurasaiteja** [comment]
Same issue #345

**Comment by sandee97** [comment]
the second input's output is YES.But the output given is NO. as it is read in reverse order the look is same 
![issue1](https://user-images.githubusercontent.com/48021652/53857695-447f9b00-3ffd-11e9-9ae5-1dd493842dbf.png)
