### ISSUE TITLE
QA_Numerical Representation_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#4]
Defect Description:
In the introduction page of "Numerical Representation" experiment,the alignment of the feedback link is not clear instead feedback link should be placed as a header option like introduction and theory

Actual Result:
In the introduction page of "Numerical Representation" experiment,the alignment of the feedback link is not clear

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Numerical%20Representation/Numerical%20Representation_02_Introduction_smk.org

![feedback](https://cloud.githubusercontent.com/assets/14869397/11239120/f5b503e0-8e0f-11e5-8f6d-ef2308127502.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.

**Comment by BSravanthi** [comment]
Issue is fixed

**Comment by BSravanthi** [comment]
Issue is fixed.
