### ISSUE TITLE
QA_More on Numbers_Back to experiments

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#45]
Defect Description:
In the "More on Numbers" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  .

Actual Result:
In the "More on Numbers" experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/More%20on%20Numbers/More%20on%20Numbers_30_Back%20to%20experiments_smk.org

![12](https://cloud.githubusercontent.com/assets/14869397/11363937/d4eedf5c-92c2-11e5-9167-83aaf8a16821.png)

**Comment by sadhanareddy** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
