### ISSUE TITLE
QA_Factorials_UI

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#46]
Defect Description:
In the Landing page of  "Factorials" experiment, the 'Home' &'Problem Solving Lab' links are present outside of the page width instead the links should be placed within the page limit inorder to maintain the page utility.

Actual Result:
In the Landing page of  "Factorials" experiment,the 'Home' &'Problem Solving Lab' links are placed outside of the page width.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Factorials/Factorials_01_Usability_smk.org

![1](https://cloud.githubusercontent.com/assets/14869397/11364441/8bc17e12-92c6-11e5-845d-f7ddd4fd2af4.png)

**Comment by khushpreet-kaur** [comment]
Fixed. This bug is related to issue #145

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
