### ISSUE TITLE
QA_Factorials_ Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#47]
Defect Description:
In the introduction page of "Factorials" experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory.

Actual Result:
In the introduction page of "Factorials" experiment,the alignment of the feedback link is not clear.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Factorials/Factorials_02_Introduction_smk.org

![2](https://cloud.githubusercontent.com/assets/14869397/11364553/15280bee-92c7-11e5-8a5f-f5eddae41695.png)

**Comment by sadhanareddy** [comment]
Fixed.This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
