### ISSUE TITLE
QA_Numerical Representation_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#5]
Defect Description:
In the introduction page of "Numerical Representation" experiment,when we click on the feedback link it is redirecting to an error page(404) instead a  feedback page should get opened

Actual Result:
In the introduction page of "Numerical Representation" experiment,when we click on the feedback link it is redirecting to an error page(404) 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Numerical%20Representation/Numerical%20Representation_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11265343/93be7010-8ec1-11e5-9be7-097eda8f57b7.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine. It is redirecting to the Feedback Form. This issue is related to issue #145 .

**Comment by BSravanthi** [comment]
Issue is closed
