### ISSUE TITLE
QA_String Operations_ Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#61]
Defect Description:
In the introduction page of "String Operations" experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory .

Actual Result:
In the introduction page of "String Operations" experiment,the alignment of the feedback link is not clear.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/String%20Operations/String%20Operations_02_Introduction_smk.org

![2](https://cloud.githubusercontent.com/assets/14869397/11388390/a6665892-935b-11e5-84b0-01e332b8efcc.png)

**Comment by sravanthimodepu** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
