### ISSUE TITLE
QA_String Operations_ Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#62]
Defect Description:
In the introduction page of "String Operations" experiment,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result:
In the introduction page of "String Operations" experiment,when we click on the feedback link it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/String%20Operations/String%20Operations_03_Introduction_p1.org

![404](https://cloud.githubusercontent.com/assets/14869397/11388414/e52049b2-935b-11e5-803c-a135c4a6935f.png)

**Comment by khushpreet-kaur** [comment]
Fixed. Feedback link is working fine. It is redirecting to the Feedback Form. This issue is related to issue #145 .

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
