### ISSUE TITLE
QA_Recursion_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#75]
Defect Description:
In the introduction page of "Recursion" experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory.

Actual Result:
In the introduction page of "Recursion" experiment,the alignment of the feedback link is not clear.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Recursion/Recursion_02_Introduction_smk.org

![1](https://cloud.githubusercontent.com/assets/14869397/11434188/9853d92a-94ee-11e5-9e60-2e637de91f0f.png)

**Comment by sravanthimodepu** [comment]
Resolved. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
