### ISSUE TITLE
QA_Recursion_Back to experiment

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#87]
Defect Description:
In the "Recursion" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen inorder to view the list of experiments by the user  .

Actual Result:
In the "Recursion" experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Recursion/Recursion_30_Back%20to%20experiments_smk.org

![13](https://cloud.githubusercontent.com/assets/14869397/11434991/3f1b52a4-94fb-11e5-8710-3fa4a8feae59.png)

**Comment by sravanthimodepu** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
