### ISSUE TITLE
QA_Advanced Arithmatic_Introduction

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#89]
Defect Description:
In the introduction page of " Advanced Arithmatic " experiment,the alignment of the feedback is not clear instead feedback link should be a header option like introduction and theory.

Actual Result:
In the introduction page of " Advanced Arithmatic " experiment,the alignment of the feedback link is not clear.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Advanced%20Arithmatic/Advanced%20Arithmatic_02_Introduction_smk.org

![2](https://cloud.githubusercontent.com/assets/14869397/11435058/0b83d4ce-94fc-11e5-932c-6882e20fd841.png)

**Comment by sravanthimodepu** [comment]
Fixed. This issue is related to #145.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
