### ISSUE TITLE
Main-Page Main logo link is broken

### ISSUE THREAD

**Issue by SiddarthVijay** [virtual-labs/problem-solving-iiith#973]
### Defect Description:
Clicking on the Logo of Vlabs should take us to the main page, but this link is broken
![broken_link](https://user-images.githubusercontent.com/31479595/54491015-fa41c800-48e0-11e9-9d63-e006cdc1a0cd.png)

**Comment by arathyrose** [comment]
FIXED!!
COMMIT ID: 22bf21d
